[package]
name = "the-game-master"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy          = "0.14"
net           = { path = "../the-net" }
tokio         = { version = "1.37", features = ["rt-multi-thread"] }
